digger:
  repo:
    worker-id: ${random.int[0,31]}
    data-center-id: ${random.int[0,31]}
  mcc-key: skytech1


spring:
  redis:
    database: 2
    host: 101.35.90.82
    port: 6379
    password: darren
    lettuce:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 10
        max-wait: 5000
    timeout: 5000
  data:
    jest:
      uri: http://192.168.1.71:9200
    elasticsearch:
      cluster-name: digger-71-test
      cluster-nodes: 192.168.1.71:9300
  profiles:
    include: ons-prod
  datasource:
    url: jdbc:mysql://101.35.90.82:3306/darren_db?characterEncoding=utf8
    username: root
    password: darren
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    username: edata
    password: edata@rabbitmq
    host: mq.digger.skytech.cn
    port: 5672
    virtual-host: digger-test
    listener:
      simple:
        concurrency: 1
  mail:
    default-encoding: UTF-8
    host: smtp.263.net
    port: 25
    username: sys.message@skytech.cn
    password: shtq365
    properties:
      email:
        smtp:
          ssl:
            enable: false
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.darren.demo.spring.mybatis
#  type-handlers-package: com.skytech.edata.repo.mysql.base

